Domain
linavell/TogetherLionRefactoring pull request #1
Opened 2024-06-19 04:58 UTC by linavell

2024-06-19 15:38 UTC, Cyma-s requested changes
안녕하세요, 아린님 :) 만들어주신 도메인 클래스 확인해보았습니다! 수고 많으셨어요 😊
지금 작성해주신 코드에서 궁금한 부분도 있고, 고쳐야 할 코드도 존재해서 Request Change 드립니다 :) 리뷰 남겨주신 것 확인해주시고, 리뷰 반영하셔서 다시 리뷰 요청해주세요 😄 질문에 대한 답변은 코멘트로 남겨주시면 되고, 질문이 이해가 안 되시면 카톡으로 물어봐주셔도 괜찮습니다!

2024-06-19 15:38 UTC, Cyma-s commented on src/main/java/com/arin/togetherlion/common/BaseTimeEntity.java
> +    private LocalDateTime createdDate;
접근 제어자를 private 으로 해두면 어떤 문제가 발생할 수 있을까요?

2024-06-19 15:38 UTC, Cyma-s commented on src/main/java/com/arin/togetherlion/copurchasing/domain/Copurchasing.java
> +@NoArgsConstructor
`@NoArgsConstructor` 는 왜 필요한가요?

2024-06-19 15:38 UTC, Cyma-s commented on src/main/java/com/arin/togetherlion/copurchasing/domain/Copurchasing.java
> +    @Id
`@Id` 가 자동으로 생성되도록 하려면 특정 어노테이션 설정이 더 필요합니다!

2024-06-19 15:38 UTC, Cyma-s commented on src/main/java/com/arin/togetherlion/copurchasing/domain/Copurchasing.java
> +    private Date expirationDate; // 유통기한
`Date` 와 `LocalDateTime` 은 어떤 차이점이 있나요?

2024-06-19 15:38 UTC, Cyma-s commented on src/main/java/com/arin/togetherlion/copurchasing/domain/Copurchasing.java
> +    private int totalPrice; // 상품 총 금액 (상품 금액 + 배송비)
상품 총 금액을 저장하는 것보다 상품 금액과 배송비를 따로 저장하는 게 유지보수 측면에서 더 낫습니다.

2024-06-19 15:38 UTC, Cyma-s commented on src/main/java/com/arin/togetherlion/copurchasing/domain/Copurchasing.java
> +    private int maxNumber; // 최대 상품 개수
최소 상품 개수가 최대 상품 개수보다 많은 경우는 어떻게 될까요?

2024-06-19 15:38 UTC, Cyma-s commented on src/main/java/com/arin/togetherlion/copurchasing/domain/Copurchasing.java
> +    private String buyPhotoUrl; // 상품 구매 인증샷 경로
변수 이름은 '명사'로 지어야 합니다! 지금은 동사로 시작하고 있어요 :)

2024-06-19 15:38 UTC, Cyma-s commented on src/main/java/com/arin/togetherlion/copurchasing/domain/Copurchasing.java
> +    private int totalPrice; // 상품 총 금액 (상품 금액 + 배송비)
그리고 주석을 달아주시는 것도 좋지만, 주석을 달지 않고도 코드가 잘 읽히는 게 훨씬 더 좋습니다!

2024-06-19 15:38 UTC, Cyma-s commented on src/main/java/com/arin/togetherlion/copurchasing/domain/Copurchasing.java
> +    @ManyToOne
`@ManyToOne` 의 기본 fetchType 은 무엇인가요?

2024-06-19 15:38 UTC, Cyma-s commented on src/main/java/com/arin/togetherlion/copurchasing/domain/Copurchasing.java
> +    private List<Participation> participationList = new ArrayList<>();
변수에는 Collection 의 이름을 포함하지 않는 것이 좋습니다. `participants` 와 같이 작명해주세요!

2024-06-19 15:38 UTC, Cyma-s commented on src/main/java/com/arin/togetherlion/copurchasing/domain/Participation.java
> +    private Copurchasing copurchasing;
왜 `Copurchasing` 과 `Participation` 과의 양방향 관계를 만들어주셨나요?

2024-06-19 15:38 UTC, Cyma-s commented on src/main/java/com/arin/togetherlion/copurchasing/domain/Participation.java
> +    }
`confirmDate` 가 null 인 경우는 언제인가요?

2024-06-19 15:38 UTC, Cyma-s commented on src/main/java/com/arin/togetherlion/point/domain/Point.java
> +        }
이 부분은 validation 함수로 따로 분리해주세요!

2024-06-19 15:38 UTC, Cyma-s commented on src/main/java/com/arin/togetherlion/point/domain/Point.java
> +    public void plusPoint(int amount) {
point 는 이미 해당 객체의 이름이기 때문에 메서드 이름은 `plus` 로만 해주시는 게 좋을 것 같아요!

2024-06-19 15:38 UTC, Cyma-s commented on src/main/java/com/arin/togetherlion/user/domain/User.java
> +    }
여기에서 상대 엔티티의 상태는 업데이트 하지 않아도 괜찮을까요?
ex. `participation.user = this;`

2024-06-19 15:38 UTC, Cyma-s commented on src/main/java/com/arin/togetherlion/copurchasing/domain/Copurchasing.java
> +    private Date tradeDate; // 거래희망일자
모집 마감 일자가 거래 희망 일자보다 더 이르다면 어떻게 될까요?

2024-06-19 15:38 UTC, Cyma-s commented on src/main/java/com/arin/togetherlion/copurchasing/domain/Copurchasing.java
> +@AllArgsConstructor
여기서 `@AllArgsConstructor` 가 필요한 이유는 무엇인가요?

2024-06-19 15:38 UTC, Cyma-s commented on src/main/java/com/arin/togetherlion/user/domain/User.java
> +    private String nickname;
email, password, nickname 의 각각의 제약 조건은 무엇인가요?
각 필드는 중요한 데이터인 만큼, 생성할 때마다 validation 을 반드시 해주어야 합니다.

2024-06-19 15:38 UTC, Cyma-s commented on src/main/java/com/arin/togetherlion/user/domain/User.java
> +    private List<Participation> participationList = new ArrayList<>();
해당 관계가 필요한 이유는 무엇인가요?

2024-06-19 15:38 UTC, Cyma-s commented on src/main/java/com/arin/togetherlion/common/BaseTimeEntity.java
> +public abstract class BaseTimeEntity {
`BaseTimeEntity` 로 createdDate, modifiedDate 를 분리해서 만들어주신 이유가 있을까요?

2024-06-19 15:38 UTC, Cyma-s commented on src/main/java/com/arin/togetherlion/copurchasing/domain/Copurchasing.java
> +    private String content;
title, content 의 길이 제한은 어느 정도인가요? 데이터가 공백으로 채워져도 괜찮을까요?

2024-06-19 15:38 UTC, Cyma-s commented on src/main/java/com/arin/togetherlion/copurchasing/domain/Copurchasing.java
> +    private User user;
여기서 `user` 연관관계가 중요한가요?

2024-06-22 03:14 UTC, eggnee commented on src/main/java/com/arin/togetherlion/common/BaseTimeEntity.java
> +    private LocalDateTime createdDate;
private 으로 선언하더라도 Lombok의 `@Getter` 어노테이션을 사용하면 상속받는 클래스에서 getCreatedDate() 메서드를 통해 접근할 수 있지 않나요?!

2024-06-22 03:14 UTC, eggnee commented on src/main/java/com/arin/togetherlion/common/BaseTimeEntity.java
> +public abstract class BaseTimeEntity {
현재 상황에선 modifiedDate는 필요 없을 것 같네요..!!!

2024-06-22 03:14 UTC, eggnee commented on src/main/java/com/arin/togetherlion/copurchasing/domain/Copurchasing.java
> +@NoArgsConstructor
@AllArgsConstructor는 모든 필드를 가지는 생성자를 만들어주고
@NoArgsConstructor는 어떤 필드도 가지지 않는 기본 생성자를 만들어줍니다.

@NoArgsConstructor는 Java의 ORM 기술인 JPA에서 기본적으로 요구하는 어노테이션으로 없으면 에러가 납니다.
@Entity를 붙이면 생성자가 따로 없을 시 자동으로 기본 생성자를 생성해주기 때문에 @NoArgsConstructor와 같은 효과를 주지만 @AllArgsConstructor를 붙였기 때문에 따로 @NoArgsConstructor 어노테이션을 붙여줘야 합니다.

2024-06-22 03:14 UTC, eggnee commented on src/main/java/com/arin/togetherlion/copurchasing/domain/Copurchasing.java
> +    @Id
넵 ㅎㅎ

2024-06-22 03:14 UTC, eggnee commented on src/main/java/com/arin/togetherlion/copurchasing/domain/Copurchasing.java
> +    private Date expirationDate; // 유통기한
`Date` Java의 오래된 날짜 및 시간 클래스로, 시간대 정보를 포함하며 변경 가능한 특성을 가지고
`LocalDateTime` Java 8에서 도입된 새로운 날짜 및 시간 API 클래스로, 시간대 정보를 포함하지 않고 불변성을 가집니다.
Java 8 이후의 프로젝트에서는 `LocalDateTime`을 사용하여 날짜와 시간을 처리하는 것이 권장됩니다. 수정하겠습니다!!!

2024-06-22 03:14 UTC, eggnee commented on src/main/java/com/arin/togetherlion/copurchasing/domain/Participation.java
> +    }
> `confirmDate` 가 null 인 경우는 언제인가요?

사용자들이 아직 구매확정 버튼을 누르지 않았을 경우입니다

2024-06-22 03:14 UTC, eggnee commented on src/main/java/com/arin/togetherlion/user/domain/User.java
> +    }
> 여기에서 상대 엔티티의 상태는 업데이트 하지 않아도 괜찮을까요? ex. `participation.user = this;`

Participation 객체 생성 시 user 객체를 설정해주므로 필요 없다고 생각했습니다..!

2024-06-22 03:14 UTC, eggnee commented on src/main/java/com/arin/togetherlion/user/domain/User.java
> +    private List<Participation> participationList = new ArrayList<>();
> 해당 관계가 필요한 이유는 무엇인가요?

회원 입장에서 자신이 참여한 공동구매와 자신이 작성한 (진행하는) 공동구매 게시물을 조회하기 위해 필요하다고 생각했습니다!!

2024-06-22 03:14 UTC, eggnee commented on src/main/java/com/arin/togetherlion/copurchasing/domain/Copurchasing.java
> +    private User user;
> 여기서 `user` 연관관계가 중요한가요?

작성자라 중요하지 않나요?!...

2024-06-22 03:14 UTC, eggnee commented on src/main/java/com/arin/togetherlion/copurchasing/domain/Participation.java
> +    private Copurchasing copurchasing;
> 왜 `Copurchasing` 과 `Participation` 과의 양방향 관계를 만들어주셨나요?

공동구매 게시물에 공동구매 참여자들을 나타내기 위해 양방향 관계로 설정했습니다!

2024-06-22 03:14 UTC, eggnee commented on src/main/java/com/arin/togetherlion/point/domain/Point.java
> +        }
> 이 부분은 validation 함수로 따로 분리해주세요!

이 방식을 사용하면 생성자가 더 간결하고 명확해지며, 유효성 검사 로직을 분리하여 재사용성이 높아지는군요~!!! 감사합니다.

2024-06-22 03:14 UTC, eggnee commented on src/main/java/com/arin/togetherlion/copurchasing/domain/Copurchasing.java
> +    @ManyToOne
> `@ManyToOne` 의 기본 fetchType 은 무엇인가요?

FetchType.EAGER로 즉시 로딩이 기본 값입니다. FetchType.EAGER를 사용하면 데이터베이스에서 불필요한 데이터를 로드할 수 있으므로 기본적으로는 LAZY를 사용하는 것이 좋습니다! 수정하겠습니다.

2024-06-23 14:23 UTC, Cyma-s commented on src/main/java/com/arin/togetherlion/common/BaseTimeEntity.java
> +    private LocalDateTime createdDate;
해당 필드는 `private` 으로 둘 필요가 없는 필드입니다. `createdDate` 는 자식 클래스에서도 접근이 가능해야 하는 필드이기 때문이죠 :) 그래서 `getter` 를 통해 간접적으로 호출하는 것보다, protected 로 접근 제어자를 변경해주는 것이 좋습니다.

2024-07-02 08:53 UTC, merged