공동구매 작성, 삭제 기능 구현 및 테스트 작성
linavell/TogetherLionRefactoring pull request #3
Opened 2024-06-28 07:12 UTC by linavell

## 📟 연결된 이슈
#2

## 👷 작업한 내용
- 공동구매 작성, 삭제 기능 구현
- 공동구매 작성, 삭제 기능 테스트 작성

2024-06-30 13:44 UTC, Cyma-s requested changes
안녕하세요 아린님! 기능 구현하시느라 수고 많으셨습니다 :)
테스트 작성이 생소하셨을 텐데 꼼꼼하게 작성해주신 부분 좋았습니다 👍🏻👍🏻👍🏻
지금 작성해주신 코드의 의도와 관련해서 질문할 부분들이 몇 가지 있어 리뷰 남겨두었습니다! 시간 되실 때 확인해주시고 다시 리뷰 요청해주세요 :) 파이팅입니다!

2024-06-30 13:44 UTC, Cyma-s commented on src/main/java/com/arin/togetherlion/copurchasing/controller/CopurchasingController.java
> +    @Autowired
`@RequiredArgsConstructor` 와 함께 `@Autowired` 를 써주신 이유가 있나요?

2024-06-30 13:44 UTC, Cyma-s commented on src/main/java/com/arin/togetherlion/copurchasing/controller/CopurchasingController.java
> +@Validated
`@Validated` 어노테이션은 어떤 기능을 하나요?

2024-06-30 13:44 UTC, Cyma-s commented on src/main/java/com/arin/togetherlion/copurchasing/controller/CopurchasingController.java
> +    @PostMapping("/copurchasings")
`@PostMapping` 과 `@DeleteMapping` 의 url 이 모두 `/copurchasings` 로 시작하고 있기 때문에, Controller 에 `@RequestMapping` 을 설정해주는 것이 중복 제거에 도움이 될 것 같네요 :)

2024-06-30 13:44 UTC, Cyma-s commented on src/main/java/com/arin/togetherlion/copurchasing/controller/CopurchasingController.java
> +    public ResponseEntity<String> delete(@PathVariable Long copurchasingId, @RequestBody Long userId) {
왜 `String` 을 반환하시나요?

2024-06-30 13:44 UTC, Cyma-s commented on src/main/java/com/arin/togetherlion/copurchasing/controller/CopurchasingController.java
> +        }
여기서 status 를 설정해주는 것보다, 커스텀 `ControllerAdvice` 를 사용하여 예외 처리하는 게 더 좋습니다. controller 단에서 status 를 직접 설정해주게 되면 status 가 여러 개 생길 때마다 if 문이 추가되어 가독성도 좋지 않고, 확장성도 좋지 않습니다.
`ControllerAdvice` 에 대해 공부해 보신 후 어떤 역할을 하고 왜 필요한지 코멘트로 남겨주시고, 이후 커밋에 반영해주세요!

2024-06-30 13:44 UTC, Cyma-s commented on src/main/java/com/arin/togetherlion/copurchasing/controller/CopurchasingController.java
> +        return ResponseEntity.ok().build();
삭제가 성공적으로 완료되었을 때 200 OK status 가 클라이언트로 전달되는 게 정말 맞을까요?

2024-06-30 13:44 UTC, Cyma-s commented on src/main/java/com/arin/togetherlion/copurchasing/domain/Copurchasing.java
> +    @Size(min = 1, max = 20)
해당 validation 은 적용이 될까요?

2024-06-30 13:44 UTC, Cyma-s commented on src/main/java/com/arin/togetherlion/copurchasing/domain/Participation.java
> +    }
아래 쪽에 줄 바꿈을 추가해주세요!

2024-06-30 13:44 UTC, Cyma-s commented on src/main/java/com/arin/togetherlion/copurchasing/domain/dto/CopurchasingCreateRequest.java
> +@NoArgsConstructor
접근 제어자를 default 로 설정해주어야만 json 파싱이 가능할까요?

2024-06-30 13:44 UTC, Cyma-s commented on src/main/java/com/arin/togetherlion/copurchasing/repository/CopurchasingRepository.java
> +@Repository
`@Repository` 어노테이션이 `ParticipationRepository` 에는 붙여져 있지 않은데요, 어노테이션을 붙이거나 붙이지 않거나 둘 중의 하나의 경우로 컨벤션을 통일해주세요!

2024-06-30 13:44 UTC, Cyma-s commented on src/main/java/com/arin/togetherlion/copurchasing/service/CopurchasingService.java
> +            throw new AccessDeniedException("게시물 작성자만 삭제할 수 있습니다.");
해당 예외가 여기서 던져지는 맥락이 옳지 않은 것 같아요. `AccessDeniedException` 은 원래 어떤 경우에 사용되고, 현재는 어떤 상황인지 알아보시고 코멘트로 남겨주세요 :)

2024-06-30 13:44 UTC, Cyma-s commented on src/main/java/com/arin/togetherlion/copurchasing/service/CopurchasingService.java
> +    }
`Copurchasing` 이 현재 시작된 상태인지 아닌지 검증하는 책임은 `Service` 가 가져야 할 책임이 아닌 것 같아요. 해당 기능은 누구의 책임일까요?

2024-06-30 13:44 UTC, Cyma-s commented on src/main/java/com/arin/togetherlion/copurchasing/service/CopurchasingService.java
> +        else
`else` 가 필요할까요?!

2024-06-30 13:44 UTC, Cyma-s commented on src/main/java/com/arin/togetherlion/copurchasing/service/CopurchasingService.java
> +        if (!userId.equals(copurchasing.getWriter().getId()))
해당 if 문을 검증하는 책임도 service 가 아닌 다른 객체의 책임처럼 보이네요 🤔

2024-06-30 13:44 UTC, Cyma-s commented on src/main/java/com/arin/togetherlion/point/domain/Point.java
> +@NoArgsConstructor
최소한의 접근 제어자로 설정해주세요!

2024-06-30 13:44 UTC, Cyma-s commented on src/main/java/com/arin/togetherlion/point/domain/Point.java
> +    public void plus(int amount) {
해당 메서드의 `amount` 값에 음수가 입력된다면 어떻게 될까요?

2024-06-30 13:44 UTC, Cyma-s commented on src/main/java/com/arin/togetherlion/user/domain/User.java
> +@Table(name = "Users")
테이블의 이름은 대문자로 작성하지 않고, 복수형을 사용하지 않는 것이 컨벤션입니다!
다른 이름을 사용해주시면 좋을 것 같습니다 :)

2024-06-30 13:44 UTC, Cyma-s commented on src/main/java/com/arin/togetherlion/user/domain/User.java
> +        this.point = new Point();
`NoArgsConstructor` 를 사용해서 데이터를 초기화해주셨는데, 이렇게 초기화하게 되면 개발자가 int 의 초기값이 0이라는 사실까지 알고 개발을 해야 합니다. 개발자의 인지 부하를 줄이기 위해서는 직접 제작하신 생성자를 사용하시거나, 기본 생성자에 amount 를 0으로 초기화하는 로직을 넣어주시는 것이 좋습니다.

2024-06-30 13:44 UTC, Cyma-s commented on src/main/resources/application.properties
> +server.port= 8088
포트가 8088인 이유가 따로 있을까요?

2024-06-30 13:44 UTC, Cyma-s commented on src/test/java/com/arin/togetherlion/copurchasing/controller/CopurchasingControllerTest.java
> +@MockBean(JpaMetamodelMappingContext.class)
해당 어노테이션을 붙여야 하는 상황이 따로 있었을까요?

2024-06-30 13:44 UTC, Cyma-s commented on src/test/java/com/arin/togetherlion/copurchasing/controller/CopurchasingControllerTest.java
> +        Long copurchasingId = 1L;
만약 현재 데이터베이스의 id 가 1L 로 시작하지 않는다면 해당 테스트는 어떻게 될까요?

2024-06-30 13:44 UTC, Cyma-s commented on src/test/java/com/arin/togetherlion/copurchasing/controller/CopurchasingControllerTest.java
> +    @DisplayName("유효한 요청 시 201 응답을 반환한다.")
테스트의 내용과 DisplayName 이 서로 다른 내용을 전달하고 있네요

2024-06-30 13:44 UTC, Cyma-s commented on src/test/java/com/arin/togetherlion/copurchasing/domain/CopurchasingTest.java
> +    @DisplayName("최소 상품 개수가 최대 상품 개수보다 크다면 예외가 발생한다.")
테스트 이름 잘 작성해주셨네요 👍

2024-06-30 13:44 UTC, Cyma-s commented on src/test/java/com/arin/togetherlion/copurchasing/domain/CopurchasingTest.java
> +        LocalDateTime wrongTradeDate = wrongDeadlineDate.minus(Period.ofDays(5));
변수 이름 구체적으로 지어주신 것 훌륭합니다 👍🏻

2024-06-30 13:44 UTC, Cyma-s commented on src/test/java/com/arin/togetherlion/copurchasing/domain/CostTest.java
> +    }
해당 테스트들이 서로 다른 클래스에 대한 테스트이기 때문에 서로 다른 클래스로 분리하면 좋을 것 같아요!

2024-06-30 13:44 UTC, Cyma-s commented on src/test/java/com/arin/togetherlion/copurchasing/service/CopurchasingServiceTest.java
> +        Long notExistedUserId = 0L;
아예 발생할 수 없는 값을 설정해둔 것 좋습니다 👍🏻

2024-06-30 13:44 UTC, Cyma-s commented on src/test/java/com/arin/togetherlion/copurchasing/service/CopurchasingServiceTest.java
> +        }
try-catch 로 감싸주신 이유는 현재 메서드에서 명시적으로 `AccessDeniedException` 을 리턴하고 있기 때문이라고 생각합니다. 그렇다면 해당 코드를 try-catch 로 래핑하지 않고 테스트 코드를 작성하기 위해서는 어떻게 해야 할까요?

2024-07-02 09:12 UTC, linavell commented on src/main/java/com/arin/togetherlion/copurchasing/controller/CopurchasingController.java
> +@Validated
> `@Validated` 어노테이션은 어떤 기능을 하나요?

`@Validated`는 Spring Framework에서 제공하는 애노테이션으로 메서드 파라미터에 대한 유효성 검사를 활성화하고 그룹 기반 유효성 검사에도 사용됩니다. `@Valid`는 단순 유효성 검사만 수행한다는 차이점이 있습니다. 현재는 그룹 기반 유효성 검사가 필요하지 않기에 `@Validated`를 붙이지 않아도 될 것 같습니다..!

2024-07-02 09:28 UTC, linavell commented on src/main/resources/application.properties
> +server.port= 8088
> 포트가 8088인 이유가 따로 있을까요?

넵 다른 프로젝트 구현하던 게 있어서..! 바꿔서 쓰고 있습니다 ㅠ

2024-07-02 09:48 UTC, linavell commented on src/test/java/com/arin/togetherlion/copurchasing/controller/CopurchasingControllerTest.java
> +@MockBean(JpaMetamodelMappingContext.class)
> 해당 어노테이션을 붙여야 하는 상황이 따로 있었을까요?
https://velog.io/@arin/Springboot-JPA-Auditing-%EC%82%AC%EC%9A%A9
해당 블로그를 참고하여 붙였습니다!

2024-07-03 02:22 UTC, Cyma-s commented on src/main/java/com/arin/togetherlion/copurchasing/controller/CopurchasingController.java
> +@Validated
훌륭합니다 👍👍

2024-07-03 02:24 UTC, Cyma-s commented on src/test/java/com/arin/togetherlion/copurchasing/controller/CopurchasingControllerTest.java
> +@MockBean(JpaMetamodelMappingContext.class)
오호 현재 JPAAuditing 을 사용하고 있어서 해당 어노테이션을 사용하고 계셨군요! 확인했습니다 :)

2024-07-03 05:35 UTC, linavell commented on src/main/java/com/arin/togetherlion/copurchasing/domain/dto/CopurchasingCreateRequest.java
> +@NoArgsConstructor
> 접근 제어자를 default 로 설정해주어야만 json 파싱이 가능할까요?

기본 생성자를 private 또는 protected로 제한하고 데이터를 전달받기 위한 생성자를 public으로 선언하게 된다면 우선 순위가 높은 public 생성자를 통해 객체를 생성하고 데이터를 전달 받아 무분별한 객체 생성을 방지할 수 있습니다!

2024-07-03 05:58 UTC, linavell commented on src/main/java/com/arin/togetherlion/copurchasing/service/CopurchasingService.java
> +            throw new AccessDeniedException("게시물 작성자만 삭제할 수 있습니다.");
> 해당 예외가 여기서 던져지는 맥락이 옳지 않은 것 같아요. `AccessDeniedException` 은 원래 어떤 경우에 사용되고, 현재는 어떤 상황인지 알아보시고 코멘트로 남겨주세요 :)

AccessDeniedException은 사용자가 인증되었지만 필요한 권한이나 역할이 없어 특정 리소스에 접근할 수 없을 때 발생하는 예외입니다!

2024-07-03 07:13 UTC, Cyma-s requested changes
안녕하세요 아린님! 많은 리뷰 열심히 반영해주시느라 수고 많으셨습니다 :) 코드가 많이 깔끔해져서 리뷰하기 수월했습니다 ☺️
몇 가지 수정 사항이 있어서 리뷰 조금 더 남겼습니다! 조금만 더 파이팅입니다 🔥

2024-07-03 07:13 UTC, Cyma-s commented on src/main/java/com/arin/togetherlion/common/ErrorCode.java
> +    private final String code;				// ACCOUNT-001
Code 는 어떤 경우에 사용되나요?

2024-07-03 07:13 UTC, Cyma-s commented on src/main/java/com/arin/togetherlion/common/ErrorResponseEntity.java
> +@Data
`@Data` 어노테이션은 `setter` 도 함께 만들어주기 때문에 지양해야 합니다!! 🔥🔥

2024-07-03 07:13 UTC, Cyma-s commented on src/main/java/com/arin/togetherlion/copurchasing/controller/CopurchasingController.java
> +    private final CopurchasingService copurchasingService;
👍👍

2024-07-03 07:13 UTC, Cyma-s commented on src/main/java/com/arin/togetherlion/copurchasing/controller/CopurchasingController.java
> +    public ResponseEntity<String> delete(@PathVariable(name = "copurchasingId") Long copurchasingId, @RequestBody Long userId) {
`@RequestBody` 가 사용되었네요?! 붙여주신 이유가 무엇일까요?

2024-07-03 07:13 UTC, Cyma-s commented on src/main/java/com/arin/togetherlion/copurchasing/domain/Copurchasing.java
> +    public boolean isStarted() {
아주 깔끔합니다 👍👍👍

2024-07-03 07:13 UTC, Cyma-s commented on src/main/java/com/arin/togetherlion/copurchasing/controller/CopurchasingController.java
> +    public ResponseEntity<String> delete(@PathVariable(name = "copurchasingId") Long copurchasingId, @RequestBody Long userId) {
그리고 아직 String 을 리턴하고 있네요 🤔🤔

2024-07-03 07:13 UTC, Cyma-s commented on src/main/java/com/arin/togetherlion/common/CustomExceptionHandler.java
> +        return ErrorResponseEntity.toResponseEntity(e.getErrorCode());
여기에서 ErrorResponseEntity 를 생성하는 로직이 ErrorResponseEntity 내부에 존재하도록 만들어주신 이유가 궁금해요!

2024-07-03 07:13 UTC, Cyma-s commented on src/main/java/com/arin/togetherlion/common/CustomException.java
> +public class CustomException extends RuntimeException {
런타임 예외를 잘 상속 받아주셨습니다 👍👍

2024-07-03 07:13 UTC, Cyma-s commented on src/main/java/com/arin/togetherlion/copurchasing/service/CopurchasingService.java
> +                .orElseThrow(() -> new IllegalArgumentException("존재하지 않는 사용자입니다."));
해당 예외는 어디서 처리될까요?

2024-07-03 07:13 UTC, Cyma-s commented on src/main/java/com/arin/togetherlion/copurchasing/service/CopurchasingService.java
> +        if (!writer.compareById(userId))
로직을 `User` 내부로 이동시킨 점은 훌륭합니다 👍
다만 메서드 이름이 `isSameUser` 와 같이 "어떤 의미있는 동작을 수행하는지" 알 수 있으면 더 좋을 것 같습니다 :)

2024-07-03 07:13 UTC, Cyma-s commented on src/main/java/com/arin/togetherlion/point/domain/Point.java
> +        validateAmount(amount);
여기서는 조금 다른 예외가 적용되어야 할 것 같아요. Plus 에서 음수 값이 들어오는 경우가 '잘못된' 경우인지, 음수 값이 들어와도 데이터 업데이트를 했을 때 amount 가 음수가 되지 않는다면 괜찮을지 같은 비즈니스 로직을 좀 더 생각해보시면 좋을 것 같습니다!!

2024-07-03 07:13 UTC, Cyma-s commented on src/main/java/com/arin/togetherlion/user/domain/User.java
> +        return true;
```suggestion
       return this.id.equals(otherUserId)
```
 이렇게 작성해도 되겠네요!

2024-07-03 07:13 UTC, Cyma-s commented on src/test/java/com/arin/togetherlion/copurchasing/controller/CopurchasingControllerTest.java
> +                .andExpect(status().isNoContent());
좋습니다 👍👍

2024-07-03 07:13 UTC, Cyma-s commented on src/test/java/com/arin/togetherlion/copurchasing/service/CopurchasingServiceTest.java
> +    void delete2() {
테스트 이름이 자세하면 더 좋겠습니다!

2024-07-03 07:13 UTC, Cyma-s commented on src/test/java/com/arin/togetherlion/copurchasing/service/CopurchasingServiceTest.java
> +                .isInstanceOf(CustomException.class);
이런 CustomException 을 테스트한다면 각 CustomException 마다 다른 부분인 ErrorCode 까지 체크하는 것이 더 확실할 것 같습니다!

2024-07-04 07:07 UTC, linavell commented on src/main/java/com/arin/togetherlion/common/ErrorCode.java
> +    private final String code;				// ACCOUNT-001
> Code 는 어떤 경우에 사용되나요?

` code`는 에러를 구분하거나 식별하는 용도로 사용되며 API 응답에서 클라이언트에게 추가적인 정보를 제공하는 데 사용됩니다

2024-07-04 07:12 UTC, linavell commented on src/main/java/com/arin/togetherlion/copurchasing/controller/CopurchasingController.java
> +    public ResponseEntity<String> delete(@PathVariable(name = "copurchasingId") Long copurchasingId, @RequestBody Long userId) {
> `@RequestBody` 가 사용되었네요?! 붙여주신 이유가 무엇일까요?

userId는 url 경로상에 표시하면 안될 것 같았습니다..!!!

2024-07-04 07:17 UTC, linavell commented on src/main/java/com/arin/togetherlion/common/CustomExceptionHandler.java
> +        return ErrorResponseEntity.toResponseEntity(e.getErrorCode());
> 여기에서 ErrorResponseEntity 를 생성하는 로직이 ErrorResponseEntity 내부에 존재하도록 만들어주신 이유가 궁금해요!

https://velog.io/@rungoat/SpringBoot-Custom-Exception-%EC%B2%98%EB%A6%AC
`ErrorResponseEntity`로 변환하는 과정은 해당 클래스의 책임으로 볼 수 있기 때문에 그 메서드를` ErrorResponseEntity` 클래스 내부에 포함시키는 것이 적절하다고 생각합니다!

2024-07-04 07:20 UTC, linavell commented on src/main/java/com/arin/togetherlion/user/domain/User.java
> +        return true;
> 이렇게 작성해도 되겠네요!

짱이네여!!!!!!!!!

2024-07-04 07:28 UTC, linavell commented on src/main/java/com/arin/togetherlion/copurchasing/service/CopurchasingService.java
> +                .orElseThrow(() -> new IllegalArgumentException("존재하지 않는 사용자입니다."));
> 해당 예외는 어디서 처리될까요?

HTTP 500 상태 코드와 함께 기본 에러 응답으로 반환된다고 합니다!!! 얘도 CustomException 과 같이 핸들러로 처리해줘야 하나요?

2024-07-13 05:03 UTC, merged