공동구매 참여 기능 구현 및 테스트 코드 작성
linavell/TogetherLionRefactoring pull request #5
Opened 2024-07-04 06:59 UTC by linavell

2024-07-11 05:37 UTC, Cyma-s requested changes
안녕하세요 아린님! 이번에 테스트를 정말 꼼꼼하게 짜주셨네요 👍👍👍 매우 안정적인 코드를 작성해주신 것 같아요. 조금 살펴볼 부분에만 리뷰 남겼는데, 시간 되시면 확인해주세요~ 감사합니다!

2024-07-11 05:37 UTC, Cyma-s commented on src/main/java/com/arin/togetherlion/common/CustomExceptionHandler.java
> +@ControllerAdvice
`@RestControllerAdvice` 라는 어노테이션도 존재하는데요, 해당 어노테이션과는 어떤 부분이 다를까요?

2024-07-11 05:37 UTC, Cyma-s commented on src/main/java/com/arin/togetherlion/common/ErrorCode.java
> +    NO_PERMISSION(HttpStatus.UNAUTHORIZED, "삭제 권한이 없습니다.");
어떤 것을 삭제하려고 시도할 때 해당 예외가 발생하는지 조금 더 자세히 적여주셔도 될 것 같습니다!

2024-07-11 05:37 UTC, Cyma-s commented on src/main/java/com/arin/togetherlion/copurchasing/domain/Copurchasing.java
> +        writer.pay(getPaymentCost(purchaseNumber));
요 로직은 서비스가 아닌 도메인 로직에 넣어주신 이유가 있으실까요?!

2024-07-11 05:37 UTC, Cyma-s commented on src/main/java/com/arin/togetherlion/copurchasing/domain/Copurchasing.java
> +        addParticipation(new Participation(purchaseNumber, writer, getPaymentCost(purchaseNumber)));
이 도메인이 다른 도메인의 생성 로직을 갖게 되면 의존성이 강해집니다 🧐 어떻게 해결해볼 수 있을까요?

2024-07-11 05:37 UTC, Cyma-s commented on src/main/java/com/arin/togetherlion/copurchasing/domain/Copurchasing.java
> +    public void validateDelete(User writer, User deleter) {
`private` 으로 선언해주는게 좋을 것 같아요!

2024-07-11 05:37 UTC, Cyma-s commented on src/main/java/com/arin/togetherlion/copurchasing/domain/Participation.java
> +        validatePurchaseNumber(purchaseNumber);
훌륭합니다 👍👍

2024-07-11 05:37 UTC, Cyma-s commented on src/main/java/com/arin/togetherlion/copurchasing/domain/Participations.java
> +            participation.getUser().refund(participation.getPaymentPoint().getAmount());
User 에게 환불 책임을 주셨는데, participation 객체에서 user 를 꺼내서 작업해서 어떤 과정으로 처리되는지 외부로 노출되는 것 같아요. 이를 숨기기 위해 Participation 에 메서드를 하나 만드는 것은 어떨까요?

2024-07-11 05:37 UTC, Cyma-s commented on src/main/java/com/arin/togetherlion/copurchasing/domain/dto/CopurchasingCreateRequest.java
> +    private int productTotalCost;
int 는 primitive 타입이기 때문에 Null 이 될 수 없습니다. Null check 를 하기 위해서는 int 를 Integer 로 변경해주셔야 합니다!!!

2024-07-11 05:37 UTC, Cyma-s commented on src/main/java/com/arin/togetherlion/copurchasing/service/CopurchasingService.java
> +        // 이 로직을 copurchasing 안에 넣어도 될까?
좋은 고민입니다. 이 로직을 서비스에서 작성해주신 이유는 무엇이었나요??

2024-07-11 05:37 UTC, Cyma-s commented on src/main/java/com/arin/togetherlion/copurchasing/service/CopurchasingService.java
> +        copurchasing.addParticipation(participation);
지금 addParticipation 과 생성자에서 모두 Participation 객체를 생성하는 것 같은데 맞을까요?!

2024-07-11 05:37 UTC, Cyma-s commented on src/main/java/com/arin/togetherlion/user/domain/User.java
> +    public void pay(int paymentCost) {
매개변수 이름이 아주 명확하네요 👍👍

2024-07-11 05:37 UTC, Cyma-s commented on src/main/java/com/arin/togetherlion/user/repository/UserRepository.java
> +
어노테이션이 필요합니다!!

2024-07-11 05:37 UTC, Cyma-s commented on src/test/java/com/arin/togetherlion/copurchasing/controller/CopurchasingControllerTest.java
> +    @DisplayName("/coupurchasing/participate 유효한 post 요청이 아닐 시 201 요청을 반환한다. (@Valid 유효성 검사)")
설명이 더 자세하면 좋을 것 같아요!

2024-07-11 05:37 UTC, Cyma-s commented on src/test/java/com/arin/togetherlion/copurchasing/controller/CopurchasingControllerTest.java
> +class CopurchasingControllerTest {
꼼꼼한 테스트 좋습니다 👍

2024-07-11 05:37 UTC, Cyma-s commented on src/main/java/com/arin/togetherlion/user/domain/User.java
> +    public void refund(int refundCost) {
환불이라는 이름을 짓게 되면 포인트 충전시에 동일한 로직을 갖는 다른 메서드를 만들게 되어요. 
충전하는 메서드를 만든 후에 환불할 때 충전 메서드를 사용하는 것이 보다 범용적으로 사용될 수 있지 않을까요?

2024-07-11 05:37 UTC, Cyma-s commented on src/test/java/com/arin/togetherlion/copurchasing/service/CopurchasingServiceTest.java
> +        final User notWriter = User.builder()
요 부분도 given 에 포함될 수 있습니다!

2024-07-11 05:37 UTC, Cyma-s commented on src/test/java/com/arin/togetherlion/copurchasing/service/CopurchasingServiceTest.java
> +        Thread.sleep(1000);
스레드 슬립을 사용해주신 이유가 있을까요?

2024-07-11 05:43 UTC, linavell commented on src/main/java/com/arin/togetherlion/copurchasing/domain/Participations.java
> +            participation.getUser().refund(participation.getPaymentPoint().getAmount());
> User 에게 환불 책임을 주셨는데, participation 객체에서 user 를 꺼내서 작업해서 어떤 과정으로 처리되는지 외부로 노출되는 것 같아요. 이를 숨기기 위해 Participation 에 메서드를 하나 만드는 것은 어떨까요?

이거 아직 push 안 한 파일에 수정해놨어요!!

2024-07-11 05:46 UTC, linavell commented on src/test/java/com/arin/togetherlion/copurchasing/service/CopurchasingServiceTest.java
> +        Thread.sleep(1000);
> 스레드 슬립을 사용해주신 이유가 있을까요?

공동구매 게시물 작성자가 공동구매에 참여하려면 deadline 전이여야 하는데 테스트 자체가 기한 만료 후 상황을 가정하는거라 deadline을 plusseconds(1)로 해두고 스레드 슬립으로 기한 이후가 되도록 했어요

2024-07-11 07:21 UTC, linavell commented on src/main/java/com/arin/togetherlion/copurchasing/service/CopurchasingService.java
> +        // 이 로직을 copurchasing 안에 넣어도 될까?
> 좋은 고민입니다. 이 로직을 서비스에서 작성해주신 이유는 무엇이었나요??

도메인 안에 넣게 되면 `User`의 로직에 `Copurchasing`이 의존하게 된다고 생각했습니다!

2024-07-11 07:37 UTC, linavell commented on src/main/java/com/arin/togetherlion/copurchasing/domain/Copurchasing.java
> +    public void validateDelete(User writer, User deleter) {
> `private` 으로 선언해주는게 좋을 것 같아요!

얘는 서비스에서 사용합니다!!

2024-07-11 09:05 UTC, linavell commented on src/main/java/com/arin/togetherlion/common/CustomExceptionHandler.java
> +@ControllerAdvice
> `@RestControllerAdvice` 라는 어노테이션도 존재하는데요, 해당 어노테이션과는 어떤 부분이 다를까요?

웹 페이지를 반환하는 일반 컨트롤러에는 `@ControllerAdvice`를 사용하여 예외 처리와 기타 공통 로직을 정의하고
RESTful API를 반환하는 컨트롤러에는 `@RestControllerAdvice`를 사용하여 예외 처리와 공통 로직을 정의합니다

2024-07-11 10:47 UTC, Cyma-s requested changes
안녕하세요 아린님~ 빠르게 수정해주셨네요 👍🏻 그런데 이전 PR 과 비교해서 코드가 수정된 부분이 많아서, 한 번 더 Request Change 드렸습니다 😭 한 번 더 확인해주시면 감사하겠습니다!

2024-07-11 10:47 UTC, Cyma-s commented on src/main/java/com/arin/togetherlion/copurchasing/service/CopurchasingService.java
> +        System.out.println("participationId = " + participationId);
제가 놓쳤나보네요 ㅋㅋㅋ 로깅이 남아있습니다!

2024-07-11 10:47 UTC, Cyma-s commented on src/main/java/com/arin/togetherlion/copurchasing/service/CopurchasingService.java
> +        final Long participationId = participationRepository.save(participation).getId();
Cascade 옵션이 걸려있기 때문에 addParticipation 으로 추가한 로직은 명시적으로 save 해주지 않아도 영속화됩니다!

2024-07-11 10:47 UTC, Cyma-s commented on src/main/java/com/arin/togetherlion/copurchasing/service/CopurchasingService.java
> +        copurchasing.addParticipation(participation);
이 부분은 writer 의 Participation 을 만들어주는 로직이니 메서드로 분리하면 훨씬 더 흐름이 잘 보일 것 같습니다!

2024-07-11 10:47 UTC, Cyma-s commented on src/main/java/com/arin/togetherlion/user/domain/User.java
> +    public void charge(int chargeCost) {
👍

2024-07-11 10:47 UTC, Cyma-s commented on src/main/java/com/arin/togetherlion/user/domain/User.java
> +    public void charge(int chargeCost) {
getPoint 로 호출하지 않고 `point` 필드에 직접 접근해서 use, add 함수를 호출해주는 것이 좋을 듯 합니다!
`point.use(chargeCost)` 같이 써볼 수 있을 것 같네요 :)

2024-07-11 10:47 UTC, Cyma-s commented on src/main/java/com/arin/togetherlion/copurchasing/service/CopurchasingService.java
> +    public Long participationCreate(ParticipationCreateRequest request) {
`createParticipation` 이 더 적절할 것 같습니다~!

2024-07-11 10:47 UTC, Cyma-s commented on src/main/java/com/arin/togetherlion/copurchasing/service/CopurchasingService.java
> +    public void participationDelete(ParticipationDeleteRequest request) {
이 부분도 마찬가지입니다!

2024-07-11 10:47 UTC, Cyma-s commented on src/main/java/com/arin/togetherlion/copurchasing/domain/Participation.java
> +            throw new IllegalArgumentException("이미 시작한 공동구매는 참여 취소가 불가합니다.");
Participation 을 삭제할 때 Copurchasing 이 시작되었는지 판단하는 검증 로직은 서비스에서 수행하는 것이 좋습니다. 해당 객체에서 제외할 수 있는 의존은 최대한 없애는 것이 바람직합니다.

2024-07-11 10:47 UTC, Cyma-s commented on src/main/java/com/arin/togetherlion/copurchasing/domain/Copurchasing.java
> +    public void validateDelete(User deleter) {
삭제를 검증하는 로직은 도메인에 있는 것보다 서비스에 있는 것이 좋습니다.
도메인이 삭제되는 행위는 도메인의 역할이라기보다는 데이터베이스의 역할이라고 볼 수 있습니다.
따라서 도메인의 상태를 확인해서 특정 상태일 때 데이터베이스에 삭제 명령을 내리는 로직의 책임은 서비스가 가져야 합니다.

2024-07-11 10:47 UTC, Cyma-s commented on src/main/java/com/arin/togetherlion/copurchasing/service/CopurchasingService.java
> +        copurchasing.getParticipations().getParticipations().remove(participation);
Participation 을 Copurchasing 에서 제외하는 로직은 Copurchasing 의 책임이겠죠? 현재 코드는 `Copurchasing` 내부에 존재하는 `Participation` 이 리스트로 구성되어 있고, remove 가 가능하다는 정보까지 서비스가 알게 되기 때문에 `Copurchasing` 에게 삭제 책임을 위임하는 것이 바람직합니다.

2024-07-11 10:47 UTC, Cyma-s commented on src/main/java/com/arin/togetherlion/copurchasing/service/CopurchasingService.java
> +        copurchasing.charge();
`Copurchasing` 의 `charge` 메서드는 어떤 경우에 사용되나요?

2024-07-11 12:33 UTC, Cyma-s commented on src/test/java/com/arin/togetherlion/copurchasing/service/CopurchasingServiceTest.java
> +        Thread.sleep(1000);
기간이 지난 날짜로 DeadLine 을 설정하면 문제가 발생할까요?

2024-07-13 05:03 UTC, merged

2024-07-16 09:11 UTC, linavell commented on src/test/java/com/arin/togetherlion/copurchasing/service/CopurchasingServiceTest.java
> +        Thread.sleep(1000);
> 기간이 지난 날짜로 DeadLine 을 설정하면 문제가 발생할까요?

넹

2024-07-16 09:13 UTC, linavell commented on src/main/java/com/arin/togetherlion/copurchasing/service/CopurchasingService.java
> +        final Long participationId = participationRepository.save(participation).getId();
> Cascade 옵션이 걸려있기 때문에 addParticipation 으로 추가한 로직은 명시적으로 save 해주지 않아도 영속화됩니다!

save 를 안 해도 자동으로 Id도 생성이 되나요?

2024-07-16 09:29 UTC, linavell commented on src/main/java/com/arin/togetherlion/user/domain/User.java
> +    public void charge(int chargeCost) {
> getPoint 로 호출하지 않고 `point` 필드에 직접 접근해서 use, add 함수를 호출해주는 것이 좋을 듯 합니다! `point.use(chargeCost)` 같이 써볼 수 있을 것 같네요 :)

전 바보여유 ㅠㅠ

2024-07-16 09:32 UTC, linavell commented on src/main/java/com/arin/togetherlion/copurchasing/service/CopurchasingService.java
> +        copurchasing.charge();
> `Copurchasing` 의 `charge` 메서드는 어떤 경우에 사용되나요?

공동구매 삭제 시 참여자들이 낸 금액을 환급할 때 사용됩니다..! 이름을 refund()로 변경하는 것이 적절할 것 같아요

2024-07-16 09:40 UTC, linavell commented on src/main/java/com/arin/togetherlion/copurchasing/domain/Copurchasing.java
> +    public void validateDelete(User deleter) {
> 삭제를 검증하는 로직은 도메인에 있는 것보다 서비스에 있는 것이 좋습니다. 도메인이 삭제되는 행위는 도메인의 역할이라기보다는 데이터베이스의 역할이라고 볼 수 있습니다. 따라서 도메인의 상태를 확인해서 특정 상태일 때 데이터베이스에 삭제 명령을 내리는 로직의 책임은 서비스가 가져야 합니다.

`validateParticipation`과 무슨 차이인지 궁금합니다..ㅠ 어떤 유효성 검증은 도메인에 넣고 어떤 유효성 검증은 서비스단에 두는데 무슨 차이인지 모르겠습니다